# Generated by Django 5.2.3 on 2025-07-22 09:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0005_remove_semester_end_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='unique_semester_name',
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='semester',
            name='end_date',
            field=models.DateField(default=datetime.date(2025, 8, 30)),
        ),
        migrations.AlterField(
            model_name='note',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL),
        ),
    ]
