# Generated by Django 5.2.3 on 2025-07-22 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0014_set_default_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notes_app.program'),
        ),
    ]
