# Generated by Django 5.2.4 on 2025-07-22 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0017_alter_note_course_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-upload_date']},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'permissions': [('can_approve', 'Can approve student profiles')], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Date when profile was approved', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course code (e.g., CS101)', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='credits',
            field=models.PositiveIntegerField(default=3, help_text='Credit hours for this course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='Full course name', max_length=100),
        ),
        migrations.AlterField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(help_text='Programs this course belongs to', related_name='courses', to='notes_app.program'),
        ),
        migrations.AlterField(
            model_name='course',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')], help_text='Semester this course is typically taken'),
        ),
        migrations.AlterField(
            model_name='course',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')], help_text='Year this course is typically taken'),
        ),
        migrations.AlterField(
            model_name='note',
            name='course',
            field=models.ForeignKey(help_text='Course this note belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes_app.course'),
        ),
        migrations.AlterField(
            model_name='note',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Automatically extracted text from PDF'),
        ),
        migrations.AlterField(
            model_name='note',
            name='pdf_file',
            field=models.FileField(help_text='Upload PDF file', upload_to='notes/pdfs/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Title of the note', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when note was uploaded'),
        ),
        migrations.AlterField(
            model_name='note',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='User who uploaded this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_notes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='current_semester',
            field=models.ForeignKey(blank=True, help_text='Active semester instance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='notes_app.semester'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Designates whether the student profile is approved'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(blank=True, help_text="Student's academic program", null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes_app.program'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(blank=True, choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')], help_text='Current academic semester', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')], help_text='Current year of study', null=True),
        ),
    ]
