# Generated by Django 5.2.4 on 2025-07-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0022_course_semester_alter_course_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
