# Generated by Django 5.2.3 on 2025-07-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='program',
        ),
        migrations.AddField(
            model_name='course',
            name='programs',
            field=models.ManyToManyField(to='notes_app.program'),
        ),
    ]
