# Generated by Django 5.2.3 on 2025-07-22 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0004_alter_course_options_alter_note_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='end_date',
        ),
    ]
