# Generated by Django 5.2.3 on 2025-07-22 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0011_alter_studentprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='current_semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='notes_app.semester'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='notes_app.program'),
            preserve_default=False,
        ),
    ]
