# Generated by Django 5.2.3 on 2025-07-22 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0013_alter_studentprofile_program'),
    ]

    operations = [
    ]
