# Generated by Django 5.2.4 on 2025-07-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0020_alter_studentprofile_current_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='year_of_study',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')], default=1),
        ),
    ]
